[package]
name = "data-structures-rust"
version = "0.1.0"
authors = ["nodebotanist <the@nodebotani.st>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
